export const RENTALS_LIST_REQUEST = 'RENTALS_LIST_REQUEST';
export const RENTALS_LIST_SUCCESS = 'RENTALS_LIST_SUCCESS';
export const RENTALS_LIST_FAIL = 'RENTALS_LIST_FAIL';

export const MY_RENTALS_LIST_REQUEST = 'MY_RENTALS_LIST_REQUEST';
export const MY_RENTALS_LIST_SUCCESS = 'MY_RENTALS_LIST_SUCCESS';
export const MY_RENTALS_LIST_FAIL = 'MY_RENTALS_LIST_FAIL';

export const RENTAL_DETAILS_REQUEST = 'RENTAL_DETAILS_REQUEST';
export const RENTAL_DETAILS_SUCCESS = 'RENTAL_DETAILS_SUCCESS';
export const RENTAL_DETAILS_FAIL = 'RENTAL_LIST_FAIL';
export const RENTAL_DETAILS_RESET = 'RENTAL_DETAILS_RESET';

export const RENTAL_CREATE_REQUEST = 'RENTAL_CREATE_REQUEST';
export const RENTAL_CREATE_SUCCESS = 'RENTAL_CREATE_SUCCESS';
export const RENTAL_CREATE_FAILURE = 'RENTAL_CREATE_FAILURE';
export const RENTAL_CREATE_RESET = 'RENTAL_CREATE_RESET';

export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAILURE = 'BOOKING_CREATE_FAILURE';
export const CREATE_BOOKING_RESET = 'CREATE_BOOKING_RESET';

export const MY_BOOKINGS_LIST_REQUEST = 'MY_BOOKINGS_LIST_REQUEST';
export const MY_BOOKINGS_LIST_SUCCESS = 'MY_BOOKINGS_LIST_SUCCESS';
export const MY_BOOKINGS_LIST_FAIL = 'MY_BOOKINGS_LIST_FAIL';
