export const RENTALS_LIST_REQUEST = 'RENTALS_LIST_REQUEST';
export const RENTALS_LIST_SUCCESS = 'RENTALS_LIST_SUCCESS';
export const RENTALS_LIST_FAIL = 'RENTALS_LIST_FAIL';

export const RENTAL_DETAILS_REQUEST = 'RENTAL_DETAILS_REQUEST';
export const RENTAL_DETAILS_SUCCESS = 'RENTAL_DETAILS_SUCCESS';
export const RENTAL_DETAILS_FAIL = 'RENTAL_LIST_FAIL';
export const RENTAL_DETAILS_RESET = 'RENTAL_DETAILS_RESET';
